import { getSubscriptionAccess } from "@/lib/subscription";
import ConnectAccounts from "@/components/ConnectAccounts";
import LockedTeaser from "@/components/LockedTeaser";
import { Eyebrow } from "@/components/ui";
import { buildFinancialPicture, type SpendingAccount, type SpendingTransaction } from "@/lib/engine/spending";
import { buildPortfolioAnalysis, type FinancialAccountRow, type HoldingRow, type SecurityRow } from "@/lib/engine/portfolio";
import { formatCheckedDate, formatMoney, formatMonths, formatPercent, getLatestScore, requireUser } from "../_lib/dashboard";

function Snapshot({ hasLinkedAccounts, checkedDate, financialPicture, portfolioAnalysis, connectedDataError }: any) {
  const coveragePct = financialPicture.monthlyEssential > 0 ? financialPicture.guaranteedIncome / financialPicture.monthlyEssential : 0;
  return <section className="rg-card mb-8" aria-labelledby="connected-money-heading"><div><p className="rg-kicker">Your connected money</p><h2 id="connected-money-heading" className="mt-2 text-3xl font-extrabold">{hasLinkedAccounts ? "Real account-powered snapshot" : "Connect your accounts to get your real score"}</h2><p className="mt-3 text-slate-700">{hasLinkedAccounts ? `Based on your connected accounts · updated ${checkedDate}` : "Keep your quiz score, then add read-only bank and brokerage data when you are ready for real spending, cushion, and fee monitoring."}</p></div>{connectedDataError ? <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold text-amber-800">We could not load connected account data right now.</div> : hasLinkedAccounts ? <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-sm font-bold text-slate-500">Monthly essential spend</p><p className="mt-2 text-2xl font-extrabold text-ink">{formatMoney(financialPicture.monthlyEssential)}</p><p className="mt-1 text-xs text-slate-600">From connected transactions</p></div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-sm font-bold text-slate-500">Guaranteed-income coverage</p><p className="mt-2 text-2xl font-extrabold text-ink">{formatPercent(coveragePct)}</p><p className="mt-1 text-xs text-slate-600">{formatMoney(financialPicture.guaranteedIncome)}/mo guaranteed income</p></div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-sm font-bold text-slate-500">Cash-cushion months</p><p className="mt-2 text-2xl font-extrabold text-ink">{formatMonths(financialPicture.cushionMonths)}</p><p className="mt-1 text-xs text-slate-600">{formatMoney(financialPicture.cashOnHand)} connected cash</p></div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-sm font-bold text-slate-500">Portfolio + fee drag</p><p className="mt-2 text-2xl font-extrabold text-ink">{formatMoney(portfolioAnalysis.totalValue)}</p><p className="mt-1 text-xs text-slate-600">Stocks {formatPercent(portfolioAnalysis.equityPct)} · Bonds {formatPercent(portfolioAnalysis.bondPct)} · Cash {formatPercent(portfolioAnalysis.cashPct)}</p><p className="mt-2 text-sm font-bold text-slate-700">Fee drag: {formatMoney(portfolioAnalysis.feeDragAnnual ?? 0)}/yr{portfolioAnalysis.partial ? " · partial (some expense ratios are incomplete)" : ""}</p></div></div> : <div className="mt-6 rounded-2xl border border-slate-200 bg-slate-50 p-5"><p className="font-bold text-ink">No connected account snapshot yet.</p><p className="mt-2 text-sm text-slate-600">Your quiz-only score stays intact until connected data is available.</p></div>}</section>;
}

export default async function AccountsPage() {
  const { supabase, user } = await requireUser("/dashboard/accounts"); const access = await getSubscriptionAccess(user.id);
  if (!access.active) return <div className="mx-auto max-w-5xl py-8"><LockedTeaser title="Unlock connected accounts" description="Premium members can connect read-only bank and brokerage data."><ConnectAccounts institutions={[]} /></LockedTeaser></div>;
  const latest = await getLatestScore(supabase, user.id); const checkedDate = formatCheckedDate(latest?.created_at);
  const [transactionsResult, accountsResult, holdingsResult, securitiesResult, profileResult, connectedInstitutionsResult] = await Promise.all([supabase.from("transactions").select("*").eq("user_id", user.id), supabase.from("financial_accounts").select("*").eq("user_id", user.id), supabase.from("holdings").select("*").eq("user_id", user.id), supabase.from("securities").select("*"), supabase.from("profiles").select("*").eq("user_id", user.id).maybeSingle(), supabase.from("plaid_items").select("item_id,institution_name,status,created_at").eq("user_id", user.id).order("created_at", { ascending: false })]);
  const transactions = (transactionsResult.data ?? []) as SpendingTransaction[]; const accounts = (accountsResult.data ?? []) as SpendingAccount[]; const connectedDataError = transactionsResult.error || accountsResult.error || holdingsResult.error || securitiesResult.error || profileResult.error; const financialPicture = buildFinancialPicture(transactions, accounts); const portfolioAnalysis = buildPortfolioAnalysis((holdingsResult.data ?? []) as HoldingRow[], (securitiesResult.data ?? []) as SecurityRow[], accounts as FinancialAccountRow[]); const hasConnectedScore = ["connected", "monthly_rescore"].includes(String(latest?.score_source ?? "")); const hasConnectedProfile = !!profileResult.data && (accounts.length > 0 || transactions.length > 0 || (holdingsResult.data ?? []).length > 0); const hasLinkedAccounts = !connectedDataError && (hasConnectedScore || hasConnectedProfile);
  return <div className="mx-auto max-w-6xl py-8"><div className="mb-8"><Eyebrow>Accounts</Eyebrow><h1 className="mt-3 text-4xl font-extrabold sm:text-5xl">Connected money snapshot</h1></div><ConnectAccounts institutions={connectedInstitutionsResult.data ?? []} /><Snapshot hasLinkedAccounts={hasLinkedAccounts} checkedDate={checkedDate} financialPicture={financialPicture} portfolioAnalysis={portfolioAnalysis} connectedDataError={connectedDataError} /></div>;
}
